import { useSQLiteContext } from 'expo-sqlite';
import { createContext, type PropsWithChildren, useCallback, useContext, useEffect, useMemo, useState } from 'react';

import { getProfile, getSetting } from '@/storage/database';

export type AppLocale = 'en' | 'fr';

export const APP_LANGUAGE_SETTING_KEY = 'settings_language';

const english = {
  'common.tryAgain': 'Try again.',
  'common.done': 'Done',
  'common.selectOption': 'Select an option',
  'common.selectOneOrMore': 'Select one or more',
  'common.notSelected': 'not selected',
  'common.noneSelected': 'none selected',
  'status.PENDING': 'PENDING',
  'status.SYNCED': 'SYNCED',
  'status.ONLINE': 'ONLINE',
  'status.OFFLINE': 'OFFLINE',
  'nav.diagnose': 'Diagnose Crop',
  'nav.result': 'Diagnosis Result',
  'nav.farm': 'My Farm',
  'nav.sync': 'Sync Status',
  'nav.settings': 'Settings',
  'nav.market': 'Market Prices',
  'home.eyebrow': 'Offline Field Assistant',
  'home.preparing': 'Preparing your local farm workspace.',
  'home.greeting': 'Mbote, {{name}}',
  'home.subtitle': 'Capture a crop concern, keep it safely on this device, and sync when a connection is available.',
  'home.heroTitle': 'Check a Crop in the Field',
  'home.heroBody': 'Checkpoint 1 uses a local mock diagnosis while the image model is prepared.',
  'home.diagnose': 'Diagnose crop',
  'home.myFarm': 'My Farm',
  'home.profileSaved': 'Profile saved on device',
  'home.addDetails': 'Add farmer and farm details',
  'home.syncStatus': 'Sync Status',
  'home.oneWaiting': '1 record waiting',
  'home.manyWaiting': '{{count}} records waiting',
  'home.settings': 'Settings',
  'home.settingsDetail': 'Preview account and app preferences',
  'home.marketPrices': 'Market Prices',
  'home.marketPricesDetail': 'Compare static demonstration prices by crop and market',
  'home.open': 'Open →',
  'market.eyebrow': 'Offline Price Feed',
  'market.title': 'Market Prices',
  'market.subtitle': 'Compare bundled demonstration prices for supported crops and markets.',
  'market.demoBadge': 'DEMO',
  'market.demoNoticeTitle': 'Demonstration Data Only',
  'market.demoNoticeBody': 'These invented sample prices are not live quotes and must not be used for buying or selling decisions.',
  'market.cropFilter': 'Filter by Crop',
  'market.allCrops': 'All Crops',
  'market.loading': 'Pulling demonstration prices…',
  'market.loadError': 'Could Not Load Prices',
  'market.tryAgain': 'Try Again',
  'market.empty': 'No demonstration prices match this crop.',
  'market.observed': 'Demonstration date: {{date}}',
  'market.pulled': 'Pulled at {{time}}',
  'market.kilogram': 'kg',
  'market.refresh': 'Pull Prices Again',
  'onboarding.tour': 'Quick Tour {{current}} of {{total}}',
  'onboarding.subtitle': 'A short introduction to the LimaDRC field workflow.',
  'onboarding.slide1Title': 'Diagnose Crops Offline',
  'onboarding.slide1Body': 'Take or select a crop photo. LimaDRC keeps the diagnosis flow available even when your connection is unreliable.',
  'onboarding.slide2Title': 'Keep Observations Safe',
  'onboarding.slide2Body': 'Farmer, farm, and diagnosis records are saved on this device first. A network failure will not delete them.',
  'onboarding.slide3Title': 'Sync When Connected',
  'onboarding.slide3Body': 'The Sync Status screen shows records waiting to upload and marks them synced only after the backend confirms receipt.',
  'onboarding.finishError': 'Could Not Finish Setup',
  'onboarding.back': 'Back',
  'onboarding.next': 'Next',
  'onboarding.start': 'Start Using LimaDRC',
  'farm.nameRequired': 'Name Required',
  'farm.nameRequiredBody': 'Enter the farmer name before saving.',
  'farm.otherRequired': 'Other Crop Required',
  'farm.otherRequiredBody': 'Enter the name of the other crop before saving.',
  'farm.saveError': 'Could not save profile',
  'farm.firstSetup': 'First-Time Setup',
  'farm.localProfile': 'Local Profile',
  'farm.createTitle': 'Create Your Farm Profile',
  'farm.title': 'My Farm',
  'farm.onboardingSubtitle': 'Tell us about your farm. These details stay on this device and can be completed without internet.',
  'farm.subtitle': 'These details are stored on this device first and never require a connection.',
  'farm.farmerName': 'Farmer Name',
  'farm.nameExample': 'e.g. Marie Kabeya',
  'farm.province': 'Province',
  'farm.provinceExample': 'e.g. Kasaï-Central',
  'farm.territory': 'Territory',
  'farm.village': 'Village',
  'farm.preferredLanguage': 'Preferred Language',
  'farm.primaryCrops': 'Primary Crops',
  'farm.primaryCropsHint': 'Choose every crop grown on this farm.',
  'farm.otherCrop': 'Other Crop',
  'farm.otherCropHint': 'Use commas if you need to enter more than one additional crop.',
  'farm.otherCropExample': 'e.g. Beans',
  'farm.saveContinue': 'Save and Continue',
  'farm.saveLocally': 'Save Locally',
  'farm.saved': 'Farmer and farm saved locally as PENDING.',
  'farm.savedObservations': 'Saved Observations',
  'farm.noObservations': 'No observations yet. Diagnose a crop to add one.',
  'farm.confidence': '{{value}}% confidence',
  'crop.Maize': 'Maize',
  'crop.Cassava': 'Cassava',
  'crop.Rice': 'Rice',
  'crop.Other': 'Other',
  'language.English': 'English',
  'language.French': 'French',
  'language.Lingala': 'Lingala',
  'language.Swahili': 'Swahili',
  'language.Tshiluba': 'Tshiluba',
  'language.Kikongo': 'Kikongo',
  'diagnose.cameraPermission': 'Camera permission needed',
  'diagnose.cameraPermissionBody': 'Enable camera access to take a crop photo.',
  'diagnose.failed': 'Diagnosis failed',
  'diagnose.eyebrow': 'Step 1 of 2',
  'diagnose.title': 'Add a Clear Crop Photo',
  'diagnose.subtitle': 'Photograph the affected leaves in good light. The current checkpoint returns a mock cassava result.',
  'diagnose.selectedCrop': 'Selected crop',
  'diagnose.noPhoto': 'No Photo Selected',
  'diagnose.noPhotoBody': 'Use the camera or choose an existing image.',
  'diagnose.takePhoto': 'Take photo',
  'diagnose.choosePhoto': 'Choose photo',
  'diagnose.run': 'Run mock diagnosis',
  'diagnose.privacy': 'The photo is used only for the current diagnosis and is not saved with the observation.',
  'result.missing': 'Missing result',
  'result.missingBody': 'Return to Diagnose and run the analysis again.',
  'result.saveError': 'Could not save',
  'result.eyebrow': 'Mock Diagnosis',
  'result.subtitle': 'Diagnosis details and field guidance are stored on this device and remain available offline.',
  'result.photoAccessibility': 'Crop photo used for this diagnosis',
  'result.loadingPhoto': 'Loading Crop Photo',
  'result.photoUnavailable': 'Crop Photo Unavailable',
  'result.photoUnavailableBody': 'Return to Diagnose and choose the photo again.',
  'result.analyzedPhoto': 'Analyzed Crop Photo',
  'result.chooseAnother': 'Choose Another Photo',
  'result.crop': 'Crop',
  'result.confidence': 'Confidence',
  'result.diagnosisId': 'Diagnosis ID',
  'result.conditionType': 'Condition Type',
  'result.details': 'Diagnosis Details',
  'result.symptoms': 'Symptoms to Check',
  'result.noSymptoms': 'No specific symptoms are available for this result.',
  'result.additionalPhoto': 'Additional photo recommended: {{target}}',
  'result.noCurative': 'No curative treatment is listed for this condition.',
  'result.curative': 'Curative treatment options are listed for this condition.',
  'result.limitedCurative': 'Curative treatment options are limited.',
  'result.actions': 'Recommended Actions',
  'result.costLevel': 'Cost level: {{value}}',
  'result.estimatedCost': 'Estimated cost: {{value}}',
  'result.noDirectCost': 'No direct material cost listed.',
  'result.localVerification': 'Local verification required before use.',
  'result.noTreatments': 'No treatment actions are listed for this result. Continue normal crop monitoring.',
  'result.fieldSummary': 'Field Summary',
  'result.disclaimer': 'Image recognition provides a likely result, not a confirmed diagnosis. Confirm treatment, availability, and costs with a local agricultural expert.',
  'result.savedTitle': 'Saved Offline',
  'result.savedBody': 'The observation is marked PENDING and will remain on this device if the backend is unavailable.',
  'result.returnHome': 'Return Home',
  'result.save': 'Save observation',
  'code.healthy': 'Healthy',
  'code.viral': 'Viral',
  'code.fungal': 'Fungal',
  'code.bacterial': 'Bacterial',
  'code.unknown': 'Unknown',
  'code.field_management': 'Field management',
  'code.prevention': 'Prevention',
  'code.chemical': 'Chemical',
  'code.diagnosis_support': 'Diagnosis support',
  'code.expert_support': 'Expert support',
  'code.low': 'Low',
  'code.variable': 'Variable',
  'code.expensive': 'Expensive',
  'code.free': 'Free',
  'code.root': 'Root',
  'settings.eyebrow': 'Local Preferences',
  'settings.title': 'Settings',
  'settings.subtitle': 'Choose preferences for language, audio, and future notification features.',
  'settings.appPreferences': 'App Preferences',
  'settings.languageHint': 'English and French interface translations are available offline.',
  'settings.appLanguage': 'App Language',
  'settings.audioDescription': 'Save your preference for spoken field guidance. Audio is not active yet.',
  'settings.audio': 'Audio Guidance',
  'settings.notificationsDescription': 'Save your preference for future reminders. No notifications are scheduled yet.',
  'settings.notifications': 'Notifications',
  'settings.save': 'Save Settings',
  'settings.saved': 'Settings saved on this device.',
  'settings.loadError': 'Could Not Load Settings',
  'settings.saveError': 'Could Not Save Settings',
  'settings.about': 'About',
  'settings.application': 'Application',
  'settings.buildStage': 'Build Stage',
  'settings.iteration': 'Iteration 2',
  'settings.note': 'Preferences are stored locally. Saving English or French changes the interface and diagnosis guidance.',
  'sync.initial': 'Test the backend connection before syncing.',
  'sync.invalidAddress': 'Invalid address',
  'sync.invalidAddressBody': 'Enter a full address beginning with http:// or https://.',
  'sync.backendReply': 'Backend replied: {{status}}.',
  'sync.unreachable': 'Backend is unreachable.',
  'sync.partial': '{{synced}} of {{attempted}} records confirmed. {{error}}',
  'sync.nonePending': 'Backend is online. There are no pending records.',
  'sync.oneConfirmed': 'Backend confirmed 1 record.',
  'sync.manyConfirmed': 'Backend confirmed {{count}} records.',
  'sync.failed': 'Sync failed.',
  'sync.recordsRemain': '{{error}} Local records remain PENDING.',
  'sync.eyebrow': 'Offline Queue',
  'sync.title': 'Sync Status',
  'sync.subtitle': 'Records stay on this device until the prototype backend acknowledges them.',
  'sync.pendingRecords': 'Pending Records',
  'sync.never': 'Never',
  'sync.lastConfirmed': 'Last Confirmed Sync',
  'sync.address': 'Backend address',
  'sync.addressHint': "Android emulator default: http://10.0.2.2:8000. For a phone, use this computer's LAN IP.",
  'sync.test': 'Test connection',
  'sync.now': 'Sync now',
  'sync.latest': 'Latest Activity',
  'sync.rules': 'Queue Rules',
  'sync.rule1': '• Saving never requires internet.',
  'sync.rule2': '• Failed requests do not delete local data.',
  'sync.rule3': '• Only a backend acknowledgement marks a record SYNCED.',
} as const;

export type TranslationKey = keyof typeof english;
type TranslationValues = Record<string, string | number>;

const french: Record<TranslationKey, string> = {
  'common.tryAgain': 'Réessayez.',
  'common.done': 'Terminé',
  'common.selectOption': 'Sélectionnez une option',
  'common.selectOneOrMore': 'Sélectionnez une ou plusieurs options',
  'common.notSelected': 'non sélectionné',
  'common.noneSelected': 'aucune sélection',
  'status.PENDING': 'EN ATTENTE',
  'status.SYNCED': 'SYNCHRONISÉ',
  'status.ONLINE': 'EN LIGNE',
  'status.OFFLINE': 'HORS LIGNE',
  'nav.diagnose': 'Diagnostiquer une culture',
  'nav.result': 'Résultat du diagnostic',
  'nav.farm': 'Mon exploitation',
  'nav.sync': 'État de la synchronisation',
  'nav.settings': 'Paramètres',
  'nav.market': 'Prix du marché',
  'home.eyebrow': 'Assistant agricole hors ligne',
  'home.preparing': 'Préparation de votre espace agricole local.',
  'home.greeting': 'Mbote, {{name}}',
  'home.subtitle': 'Signalez un problème de culture, conservez-le sur cet appareil et synchronisez-le lorsqu’une connexion est disponible.',
  'home.heroTitle': 'Examiner une culture au champ',
  'home.heroBody': 'Le point de contrôle 1 utilise un diagnostic fictif local pendant la préparation du modèle d’image.',
  'home.diagnose': 'Diagnostiquer une culture',
  'home.myFarm': 'Mon exploitation',
  'home.profileSaved': 'Profil enregistré sur l’appareil',
  'home.addDetails': 'Ajouter les renseignements de l’agriculteur et de l’exploitation',
  'home.syncStatus': 'État de la synchronisation',
  'home.oneWaiting': '1 enregistrement en attente',
  'home.manyWaiting': '{{count}} enregistrements en attente',
  'home.settings': 'Paramètres',
  'home.settingsDetail': 'Consulter les préférences du compte et de l’application',
  'home.marketPrices': 'Prix du marché',
  'home.marketPricesDetail': 'Comparer des prix de démonstration statiques par culture et marché',
  'home.open': 'Ouvrir →',
  'market.eyebrow': 'Prix disponibles hors ligne',
  'market.title': 'Prix du marché',
  'market.subtitle': 'Comparez les prix de démonstration intégrés pour les cultures et marchés pris en charge.',
  'market.demoBadge': 'DÉMO',
  'market.demoNoticeTitle': 'Données de démonstration uniquement',
  'market.demoNoticeBody': 'Ces prix fictifs ne sont pas des cours en temps réel et ne doivent pas servir aux décisions d’achat ou de vente.',
  'market.cropFilter': 'Filtrer par culture',
  'market.allCrops': 'Toutes les cultures',
  'market.loading': 'Chargement des prix de démonstration…',
  'market.loadError': 'Impossible de charger les prix',
  'market.tryAgain': 'Réessayer',
  'market.empty': 'Aucun prix de démonstration ne correspond à cette culture.',
  'market.observed': 'Date de démonstration : {{date}}',
  'market.pulled': 'Chargé à {{time}}',
  'market.kilogram': 'kg',
  'market.refresh': 'Actualiser les prix',
  'onboarding.tour': 'Visite rapide {{current}} sur {{total}}',
  'onboarding.subtitle': 'Une brève présentation du fonctionnement de LimaDRC sur le terrain.',
  'onboarding.slide1Title': 'Diagnostiquer les cultures hors ligne',
  'onboarding.slide1Body': 'Prenez ou sélectionnez une photo de la culture. LimaDRC maintient le diagnostic disponible même lorsque la connexion est instable.',
  'onboarding.slide2Title': 'Conserver les observations en sécurité',
  'onboarding.slide2Body': 'Les données de l’agriculteur, de l’exploitation et du diagnostic sont d’abord enregistrées sur cet appareil. Une panne de réseau ne les supprimera pas.',
  'onboarding.slide3Title': 'Synchroniser une fois connecté',
  'onboarding.slide3Body': 'L’écran d’état affiche les enregistrements à téléverser et ne les marque comme synchronisés qu’après confirmation du serveur.',
  'onboarding.finishError': 'Impossible de terminer la configuration',
  'onboarding.back': 'Retour',
  'onboarding.next': 'Suivant',
  'onboarding.start': 'Commencer à utiliser LimaDRC',
  'farm.nameRequired': 'Nom requis',
  'farm.nameRequiredBody': 'Saisissez le nom de l’agriculteur avant d’enregistrer.',
  'farm.otherRequired': 'Autre culture requise',
  'farm.otherRequiredBody': 'Saisissez le nom de l’autre culture avant d’enregistrer.',
  'farm.saveError': 'Impossible d’enregistrer le profil',
  'farm.firstSetup': 'Première configuration',
  'farm.localProfile': 'Profil local',
  'farm.createTitle': 'Créer votre profil agricole',
  'farm.title': 'Mon exploitation',
  'farm.onboardingSubtitle': 'Présentez-nous votre exploitation. Ces renseignements restent sur cet appareil et peuvent être saisis sans Internet.',
  'farm.subtitle': 'Ces renseignements sont d’abord stockés sur cet appareil et ne nécessitent jamais de connexion.',
  'farm.farmerName': 'Nom de l’agriculteur',
  'farm.nameExample': 'p. ex. Marie Kabeya',
  'farm.province': 'Province',
  'farm.provinceExample': 'p. ex. Kasaï-Central',
  'farm.territory': 'Territoire',
  'farm.village': 'Village',
  'farm.preferredLanguage': 'Langue préférée',
  'farm.primaryCrops': 'Cultures principales',
  'farm.primaryCropsHint': 'Sélectionnez toutes les cultures de cette exploitation.',
  'farm.otherCrop': 'Autre culture',
  'farm.otherCropHint': 'Utilisez des virgules pour saisir plusieurs cultures supplémentaires.',
  'farm.otherCropExample': 'p. ex. Haricots',
  'farm.saveContinue': 'Enregistrer et continuer',
  'farm.saveLocally': 'Enregistrer localement',
  'farm.saved': 'Agriculteur et exploitation enregistrés localement avec l’état EN ATTENTE.',
  'farm.savedObservations': 'Observations enregistrées',
  'farm.noObservations': 'Aucune observation pour le moment. Diagnostiquez une culture pour en ajouter une.',
  'farm.confidence': 'confiance : {{value}} %',
  'crop.Maize': 'Maïs',
  'crop.Cassava': 'Manioc',
  'crop.Rice': 'Riz',
  'crop.Other': 'Autre',
  'language.English': 'Anglais',
  'language.French': 'Français',
  'language.Lingala': 'Lingala',
  'language.Swahili': 'Swahili',
  'language.Tshiluba': 'Tshiluba',
  'language.Kikongo': 'Kikongo',
  'diagnose.cameraPermission': 'Autorisation de la caméra requise',
  'diagnose.cameraPermissionBody': 'Autorisez l’accès à la caméra pour photographier une culture.',
  'diagnose.failed': 'Échec du diagnostic',
  'diagnose.eyebrow': 'Étape 1 sur 2',
  'diagnose.title': 'Ajouter une photo nette de la culture',
  'diagnose.subtitle': 'Photographiez les feuilles atteintes sous un bon éclairage. Le point de contrôle actuel renvoie un résultat fictif pour le manioc.',
  'diagnose.selectedCrop': 'Culture sélectionnée',
  'diagnose.noPhoto': 'Aucune photo sélectionnée',
  'diagnose.noPhotoBody': 'Utilisez la caméra ou choisissez une image existante.',
  'diagnose.takePhoto': 'Prendre une photo',
  'diagnose.choosePhoto': 'Choisir une photo',
  'diagnose.run': 'Lancer le diagnostic fictif',
  'diagnose.privacy': 'La photo sert uniquement au diagnostic en cours et n’est pas enregistrée avec l’observation.',
  'result.missing': 'Résultat manquant',
  'result.missingBody': 'Revenez au diagnostic et relancez l’analyse.',
  'result.saveError': 'Impossible d’enregistrer',
  'result.eyebrow': 'Diagnostic fictif',
  'result.subtitle': 'Les détails du diagnostic et les conseils agricoles sont stockés sur cet appareil et restent disponibles hors ligne.',
  'result.photoAccessibility': 'Photo de la culture utilisée pour ce diagnostic',
  'result.loadingPhoto': 'Chargement de la photo',
  'result.photoUnavailable': 'Photo de la culture indisponible',
  'result.photoUnavailableBody': 'Revenez au diagnostic et choisissez de nouveau la photo.',
  'result.analyzedPhoto': 'Photo de la culture analysée',
  'result.chooseAnother': 'Choisir une autre photo',
  'result.crop': 'Culture',
  'result.confidence': 'Confiance',
  'result.diagnosisId': 'Identifiant du diagnostic',
  'result.conditionType': 'Type d’affection',
  'result.details': 'Détails du diagnostic',
  'result.symptoms': 'Symptômes à vérifier',
  'result.noSymptoms': 'Aucun symptôme précis n’est disponible pour ce résultat.',
  'result.additionalPhoto': 'Photo supplémentaire recommandée : {{target}}',
  'result.noCurative': 'Aucun traitement curatif n’est indiqué pour cette affection.',
  'result.curative': 'Des traitements curatifs sont indiqués pour cette affection.',
  'result.limitedCurative': 'Les possibilités de traitement curatif sont limitées.',
  'result.actions': 'Mesures recommandées',
  'result.costLevel': 'Niveau de coût : {{value}}',
  'result.estimatedCost': 'Coût estimé : {{value}}',
  'result.noDirectCost': 'Aucun coût matériel direct indiqué.',
  'result.localVerification': 'Vérification locale requise avant utilisation.',
  'result.noTreatments': 'Aucune mesure de traitement n’est indiquée pour ce résultat. Continuez à surveiller normalement la culture.',
  'result.fieldSummary': 'Résumé pour le terrain',
  'result.disclaimer': 'La reconnaissance d’image fournit un résultat probable, et non un diagnostic confirmé. Confirmez le traitement, sa disponibilité et son coût auprès d’un spécialiste agricole local.',
  'result.savedTitle': 'Enregistré hors ligne',
  'result.savedBody': 'L’observation porte l’état EN ATTENTE et restera sur cet appareil si le serveur est indisponible.',
  'result.returnHome': 'Retour à l’accueil',
  'result.save': 'Enregistrer l’observation',
  'code.healthy': 'Sain',
  'code.viral': 'Viral',
  'code.fungal': 'Fongique',
  'code.bacterial': 'Bactérien',
  'code.unknown': 'Inconnu',
  'code.field_management': 'Gestion au champ',
  'code.prevention': 'Prévention',
  'code.chemical': 'Traitement chimique',
  'code.diagnosis_support': 'Aide au diagnostic',
  'code.expert_support': 'Appui d’un spécialiste',
  'code.low': 'Faible',
  'code.variable': 'Variable',
  'code.expensive': 'Élevé',
  'code.free': 'Gratuit',
  'code.root': 'Racine',
  'settings.eyebrow': 'Préférences locales',
  'settings.title': 'Paramètres',
  'settings.subtitle': 'Choisissez les préférences de langue, d’audio et des futures notifications.',
  'settings.appPreferences': 'Préférences de l’application',
  'settings.languageHint': 'Les interfaces en anglais et en français sont disponibles hors ligne.',
  'settings.appLanguage': 'Langue de l’application',
  'settings.audioDescription': 'Enregistrez votre préférence pour les conseils audio. L’audio n’est pas encore actif.',
  'settings.audio': 'Conseils audio',
  'settings.notificationsDescription': 'Enregistrez votre préférence pour de futurs rappels. Aucune notification n’est encore programmée.',
  'settings.notifications': 'Notifications',
  'settings.save': 'Enregistrer les paramètres',
  'settings.saved': 'Paramètres enregistrés sur cet appareil.',
  'settings.loadError': 'Impossible de charger les paramètres',
  'settings.saveError': 'Impossible d’enregistrer les paramètres',
  'settings.about': 'À propos',
  'settings.application': 'Application',
  'settings.buildStage': 'Étape de développement',
  'settings.iteration': 'Itération 2',
  'settings.note': 'Les préférences sont stockées localement. Enregistrer l’anglais ou le français modifie l’interface et les conseils de diagnostic.',
  'sync.initial': 'Testez la connexion au serveur avant de synchroniser.',
  'sync.invalidAddress': 'Adresse non valide',
  'sync.invalidAddressBody': 'Saisissez une adresse complète commençant par http:// ou https://.',
  'sync.backendReply': 'Réponse du serveur : {{status}}.',
  'sync.unreachable': 'Le serveur est inaccessible.',
  'sync.partial': '{{synced}} enregistrement(s) confirmé(s) sur {{attempted}}. {{error}}',
  'sync.nonePending': 'Le serveur est en ligne. Aucun enregistrement n’est en attente.',
  'sync.oneConfirmed': 'Le serveur a confirmé 1 enregistrement.',
  'sync.manyConfirmed': 'Le serveur a confirmé {{count}} enregistrements.',
  'sync.failed': 'Échec de la synchronisation.',
  'sync.recordsRemain': '{{error}} Les enregistrements locaux restent EN ATTENTE.',
  'sync.eyebrow': 'File d’attente hors ligne',
  'sync.title': 'État de la synchronisation',
  'sync.subtitle': 'Les enregistrements restent sur cet appareil jusqu’à leur confirmation par le serveur prototype.',
  'sync.pendingRecords': 'Enregistrements en attente',
  'sync.never': 'Jamais',
  'sync.lastConfirmed': 'Dernière synchronisation confirmée',
  'sync.address': 'Adresse du serveur',
  'sync.addressHint': 'Adresse par défaut de l’émulateur Android : http://10.0.2.2:8000. Pour un téléphone, utilisez l’adresse IP locale de cet ordinateur.',
  'sync.test': 'Tester la connexion',
  'sync.now': 'Synchroniser',
  'sync.latest': 'Activité récente',
  'sync.rules': 'Règles de la file d’attente',
  'sync.rule1': '• L’enregistrement ne nécessite jamais Internet.',
  'sync.rule2': '• Les requêtes échouées ne suppriment pas les données locales.',
  'sync.rule3': '• Seule une confirmation du serveur marque un enregistrement comme SYNCHRONISÉ.',
};

const translations: Record<AppLocale, Record<TranslationKey, string>> = {
  en: english,
  fr: french,
};

type LocalizationContextValue = {
  locale: AppLocale;
  setLocale: (locale: AppLocale) => void;
  t: (key: TranslationKey, values?: TranslationValues) => string;
};

const LocalizationContext = createContext<LocalizationContextValue | null>(null);

export function localeFromLanguage(language: string | null | undefined): AppLocale {
  return language?.trim().toLocaleLowerCase() === 'french' ||
    language?.trim().toLocaleLowerCase() === 'français'
    ? 'fr'
    : 'en';
}

export function languageFromLocale(locale: AppLocale) {
  return locale === 'fr' ? 'French' : 'English';
}

export function translate(locale: AppLocale, key: TranslationKey, values?: TranslationValues) {
  const template = translations[locale][key] ?? english[key];
  if (!values) return template;

  return template.replace(/\{\{(\w+)\}\}/g, (match, name: string) =>
    name in values ? String(values[name]) : match,
  );
}

export function LocalizationProvider({ children }: PropsWithChildren) {
  const db = useSQLiteContext();
  const [locale, setLocale] = useState<AppLocale>('en');
  const [ready, setReady] = useState(false);

  useEffect(() => {
    let active = true;

    Promise.all([getSetting(db, APP_LANGUAGE_SETTING_KEY), getProfile(db)])
      .then(([savedLanguage, profile]) => {
        if (!active) return;
        setLocale(localeFromLanguage(savedLanguage ?? profile?.farmer.preferred_language));
      })
      .catch(() => {
        if (active) setLocale('en');
      })
      .finally(() => {
        if (active) setReady(true);
      });

    return () => {
      active = false;
    };
  }, [db]);

  const t = useCallback(
    (key: TranslationKey, values?: TranslationValues) => translate(locale, key, values),
    [locale],
  );
  const value = useMemo(() => ({ locale, setLocale, t }), [locale, t]);

  if (!ready) return null;
  return <LocalizationContext.Provider value={value}>{children}</LocalizationContext.Provider>;
}

export function useTranslation() {
  const value = useContext(LocalizationContext);
  if (!value) throw new Error('useTranslation must be used within LocalizationProvider.');
  return value;
}
